[filesystem]
# Possible prefixes for harvest directories.
harvest_dir_prefixes = [
  "CHANGE ME"
]

[s3]
# AWS CLI configuration profile to use for S3 bucket credentials.
configure.profile_name = "CHANGE ME"

[s3.sync]
# Directory where local copies of thumbnails are kept.
source = "CHANGE ME"

# URI of S3 bucket where remote copies of thumbnails are kept.
destination.s3_uri = "CHANGE ME"

# Domain name of S3 bucket (static HTTP server) where remote copies of thumbnails are served from.
destination.domain_name = "CHANGE ME"

[solr]
# Base URL of the Solr index.
base_url = "CHANGE ME"

[leveldb]
[leveldb.harvester_settings]
# Where to create the harvester_settings LevelDB instance.
path = "CHANGE ME"

# Where to find the jOAI metadata for each harvest.
source.base_path = "CHANGE ME"

# Name of the file that contains metadata about jOAI's scheduled harvests.
source.files.scheduled_harvests = "SCHEDULED_5fHARVESTS"

# Java class that contains metadata for each jOAI scheduled harvest.
source.classes.scheduled_harvest = "org.dlese.dpc.oai.harvester.structs.ScheduledHarvest"

[leveldb.record_identifiers]
# Where to create the record_identifiers LevelDB instance.
path = "CHANGE ME"

[metadata]
# Regular expressions to match against fields to search for thumbnail URLs.
dublin_core.thumbnail_field_patterns = [
  "identifier\.thumbnail",
  "identifier",
  "identifier\.(?:.+)",
]
# Mapping from Dublin Core field names to Solr field names.
[metadata.dublin_core.solr_mapping]
title = "title_keyword"
creator = "creator_keyword"
subject = "subject_keyword"
description = "description_keyword"
publisher = "publisher_keyword"
contributor = "contributor_keyword"
date = "date_keyword"
type = "type_keyword"
format = "format_keyword"
identifier = "identifier_keyword"
source = "source_keyword"
language = "language_keyword"
relation = "relation_keyword"
coverage = "coverage_keyword"
rights = "rights_keyword"