[filesystem]
# Prefix for harvest directory.
harvest_dir_prefix = "CHANGE ME"

[s3]
# AWS CLI configuration profile to use for S3 bucket credentials.
configure.profile_name = "CHANGE ME"

[s3.sync]
# Directory where local copies of thumbnails are kept.
source = "CHANGE ME"

# URI of S3 bucket where remote copies of thumbnails are kept.
destination.s3_uri = "CHANGE ME"

# Domain name of S3 bucket (static HTTP server) where remote copies of thumbnails are served from.
destination.domain_name = "CHANGE ME"

[solr]
# Base URL of the Solr index.
base_url = "CHANGE ME"

[leveldb]
[leveldb.harvester_settings]
# Where to create the harvester_settings LevelDB instance.
path = "CHANGE ME"

# Where to find the jOAI metadata for each harvest.
source.base_path = "CHANGE ME"

# Name of the file that contains metadata about jOAI's scheduled harvests.
source.files.scheduled_harvests = "SCHEDULED_5fHARVESTS"

# Java class that contains metadata for each jOAI scheduled harvest.
source.classes.scheduled_harvest = "org.dlese.dpc.oai.harvester.structs.ScheduledHarvest"

[leveldb.record_sets]
# Where to create the record_sets LevelDB instance.
path = "CHANGE ME"
