FROM tomcat:latest

# Install jOAI.
RUN wget -q https://github.com/NCAR/joai-project/releases/download/v3.2/joai_v3.2.zip
RUN unzip joai_v3.2.zip

# Rather than just place oai.war in the webapps directory, we must unpack it 
# ourselves so that we can create the harvest symlink to /opt/prl/harvest
RUN ( mkdir webapps/oai && \
      cd webapps/oai && \
      jar -xf ../../joai_v3.2/oai.war )
RUN mkdir -p /opt/prl/harvest webapps/oai/WEB-INF/harvester_settings_and_data
RUN ln -s -t . /opt/prl/harvest
RUN ln -s -r -t /opt/prl/ webapps/oai/WEB-INF/harvester_settings_and_data/harvesterSettings
RUN rm -r joai_v3.2*