version: '3'
services:
  indexer:
    build:
      context: .
      args:
        - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
        - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
        - "AWS_REGION=${AWS_REGION}"
    volumes:
      - harvest:/opt/prl/harvest
      - harvester_settings:/opt/prl/harvesterSettings
    networks:
      - bridge1
    depends_on:
      - solr
    command: ["./wait-for-it.sh", "solr:8983", "--", "python", "-m", "pacific_rim_library.indexer", "-t", "/opt/prl/harvest"]
  joai:
    build:
      context: .
      dockerfile: Dockerfile-joai
    volumes:
      - harvest:/opt/prl/harvest
      - harvester_settings:/opt/prl/harvesterSettings
    network_mode: host
  solr:
    image: prl-solr:latest
    ports:
      - 8983:8983
    networks:
      - bridge1
volumes:
  harvest:
  harvester_settings:
networks:
  bridge1: