version: '3'
services:
  indexer:
    build:
      context: .
      args:
        - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
        - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
        - "AWS_REGION=${AWS_REGION}"
    volumes:
      - joai_config:/joai/config
      - joai_data:/joai/data
    networks:
      - bridge1
    depends_on:
      - solr
    command: ["./wait-for-it.sh", "solr:8983", "--", "python", "-m", "pacific_rim_library.indexer", "-t", "/joai/data"]
  joai:
    image: ncar/joai-project:3.2
    restart: unless-stopped
    volumes:
      - joai_config:/joai/config
      - joai_data:/joai/data
    ports:
      - 38080:8080
  solr:
    image: prl-solr:latest
    ports:
      - 8983:8983
    networks:
      - bridge1
volumes:
  joai_config:
  joai_data:
networks:
  bridge1:
